modLoader="javafml"
loaderVersion="[34,)"
license="The Unlicense"

[[mods]]
    modId="purpleblock"
    version="${file.jarVersion}"
    displayName="Purple Block"

    description='''

    Just a Purple Block

    '''